/*-----/translation api/------*/
export const FETCH_TRANS_PENDING = 'FETCH_TRANS_PENDING';
export const FETCH_TRANS_REJECTED = 'FETCH_TRANS_REJECTED';
export const FETCH_TRANS_FULFILLED = 'FETCH_TRANS_FULFILLED';
/*-----/constraints api/------*/
export const FETCH_CONSTRAINTS = 'FETCH_CONSTRAINTS';
export const FETCH_CONSTRAINTS_PENDING = 'FETCH_CONSTRAINTS_PENDING';
export const FETCH_CONSTRAINTS_REJECTED = 'FETCH_CONSTRAINTS_REJECTED';
export const FETCH_CONSTRAINTS_FULFILLED = 'FETCH_CONSTRAINTS_FULFILLED';
/*-----/formation api/------*/
export const FETCH_FORMATION = 'FETCH_FORMATION';
export const FETCH_FORMATION_PENDING = 'FETCH_FORMATION_PENDING';
export const FETCH_FORMATION_REJECTED = 'FETCH_FORMATION_REJECTED';
export const FETCH_FORMATION_FULFILLED = 'FETCH_FORMATION_FULFILLED';
/*-----/players api/------*/
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYERS_PENDING = 'FETCH_PLAYERS_PENDING';
export const FETCH_PLAYERS_REJECTED = 'FETCH_PLAYERS_REJECTED';
export const FETCH_PLAYERS_FULFILLED = 'FETCH_PLAYERS_FULFILLED';
/*-----/user team api/------*/
export const FETCH_USER_TEAM = 'FETCH_USER_TEAM';
export const FETCH_USER_TEAM_PENDING = 'FETCH_USER_TEAM_PENDING';
export const FETCH_USER_TEAM_REJECTED = 'FETCH_USER_TEAM_REJECTED';
export const FETCH_USER_TEAM_FULFILLED = 'FETCH_USER_TEAM_FULFILLED';
/*-----/revealed team api/------*/
export const FETCH_REVEALED_TEAM = 'FETCH_REVEALED_TEAM';
export const FETCH_REVEALED_TEAM_PENDING = 'FETCH_REVEALED_TEAM_PENDING';
export const FETCH_REVEALED_TEAM_REJECTED = 'FETCH_REVEALED_TEAM_REJECTED';
export const FETCH_REVEALED_TEAM_FULFILLED = 'FETCH_REVEALED_TEAM_FULFILLED';
/*-----/player card api/------*/
export const FETCH_PLAYER_CARD = 'FETCH_PLAYER_CARD';
export const FETCH_PLAYER_CARD_PENDING = 'FETCH_PLAYER_CARD_PENDING';
export const FETCH_PLAYER_CARD_REJECTED = 'FETCH_PLAYER_CARD_REJECTED';
export const FETCH_PLAYER_CARD_FULFILLED = 'FETCH_PLAYER_CARD_FULFILLED';
/*-----/save api/------*/
export const POST_SAVE_TEAM = 'POST_SAVE_TEAM';
export const POST_SAVE_TEAM_PENDING = 'POST_SAVE_TEAM_PENDING';
export const POST_SAVE_TEAM_REJECTED = 'POST_SAVE_TEAM_REJECTED';
export const POST_SAVE_TEAM_FULFILLED = 'POST_SAVE_TEAM_FULFILLED';
/*-----/login api/------*/
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_PENDING = 'POST_LOGIN_PENDING';
export const POST_LOGIN_REJECTED = 'POST_LOGIN_REJECTED';
export const POST_LOGIN_FULFILLED = 'POST_LOGIN_FULFILLED';
/*-----/gdpr api/------*/
export const POST_GDPR = 'POST_GDPR';
export const POST_GDPR_PENDING = 'POST_GDPR_PENDING';
export const POST_GDPR_REJECTED = 'POST_GDPR_REJECTED';
export const POST_GDPR_FULFILLED = 'POST_GDPR_FULFILLED';


export const ENABLE_DROP_MODE = 'ENABLE_DROP_MODE';
export const DROP_ITEM = 'DROP_ITEM';

export const CHANGE_MODE = 'CHANGE_MODE';
export const RESET_MODE = 'RESET_MODE';

export const SHOW_HIDE_POPUP = 'SHOW_HIDE_POPUP';
export const CHANGE_FORMATION = 'CHANGE_FORMATION';
export const AFTER_CHANGE_FORMATION = 'AFTER_CHANGE_FORMATION';
export const CREATE_EMPTY_TEAM_BY_FORMATION = 'CREATE_EMPTY_TEAM_BY_FORMATION';
export const CHANGE_SKILL_TAB = 'CHANGE_SKILL_TAB';
export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const SHOW_HIDE_PLAYERLISTING = 'SHOW_HIDE_PLAYERLISTING';
export const ADD_REMOVED_PLAYER_FROM_FORMATION = 'ADD_REMOVED_PLAYER_FROM_FORMATION';
export const REMOVE_REMOVED_PLAYER_FROM_FORMATION = 'REMOVE_REMOVED_PLAYER_FROM_FORMATION';
export const ADD_PLAYER_FOR_CARD = 'ADD_PLAYER_FOR_CARD';
export const REMOVE_PLAYER_FOR_CARD = 'REMOVE_PLAYER_FOR_CARD';

